Beacons = function Beacons(client) {
    this.client = client;
};

var blacklist = function() {
    this.client.blacklistCommonUrls();
    this.client.blacklistRequests(httpseb2 .3 lift.com., 200);
    this.client.blacklistRequests(httpss7.addthis.com., 200);
    this.client.blacklistRequests(httpcdn.mplxtms.com., 200);
    this.client.blacklistRequests(httpmatch.adsrvr.com., 200);
    this.client.blacklistRequests(httpsimage2.pubmatic.com., 200);
    this.client.blacklistRequests(httpsp.analytics.yahoo.com., 200);
    this.client.blacklistRequests(httptags.bluekai.com., 200);
    this.client.blacklistRequests(httpu.optorb.com., 200);
    this.client.blacklistRequests(https.ssl..cf2.rackcdn.com., 200);
    this.client.blacklistRequests(https20523207p.rfihub.com., 200);
    this.client.blacklistRequests(https20588869p.frihub.com., 200);
    this.client.blacklistRequests(https20588869p.rfihub.com., 200);
    this.client.blacklistRequests(https36eb5594.mpstat.us., 200);
    this.client.blacklistRequests(httpsa.collective - media.net., 200);
    this.client.blacklistRequests(httpsa.rfihub.com., 200);
    this.client.blacklistRequests(httpsa248.e.akamai.net., 200);
    this.client.blacklistRequests(httpsad.yieldmanager.com., 200);
    this.client.blacklistRequests(httpsadadvisor.net., 200);
    this.client.blacklistRequests(httpsadfarm.mediaplex.com., 200);
    this.client.blacklistRequests(httpsads.yahoo.com., 200);
    this.client.blacklistRequests(httpsanalytics.twitter.com., 200);
    this.client.blacklistRequests(httpsapis.google.com., 200);
    this.client.blacklistRequests(httpsbat.bing.com., 200);
    this.client.blacklistRequests(httpsbat.r.msn.com., 200);
    this.client.blacklistRequests(httpsc.go - mpulse.net., 200);
    this.client.blacklistRequests(httpsc0497f3d1e4a234c0037 - 9 c343f9e35978030457d8a6336c6b103., 200);
    this.client.blacklistRequests(httpsc0497f3d1e4a234c0037 - 9 c343f9e35978030457d8a6336c6b103.ssl.cf2.rackcdn.com., 200);
    this.client.blacklistRequests(httpscdn.appdynamics.com., 200);
    this.client.blacklistRequests(httpscdn.syndication.twitter.com., 200);
    this.client.blacklistRequests(httpscol.eum - appdynamics.com., 200);
    this.client.blacklistRequests(httpsdsum - sec.casalemedia.com., 200);
    this.client.blacklistRequests(httpsdx.steelhousemedia.com., 200);
    this.client.blacklistRequests(httpsei.rlcdn.com., 200);
    this.client.blacklistRequests(httpsfbstatic - a.akamaihd.net., 200);
    this.client.blacklistRequests(httpsgoku.brightcove.com., 200);
    this.client.blacklistRequests(httpsiad - login.dotomi.com., 200);
    this.client.blacklistRequests(httpsib.adnxs.com., 200);
    this.client.blacklistRequests(httpsips - invite.iperceptions.com., 200);
    this.client.blacklistRequests(httpsmatch.xg4ken.com., 200);
    this.client.blacklistRequests(httpsp.rfihub.com., 200);
    this.client.blacklistRequests(httpspixel.quantserve.com., 200);
    this.client.blacklistRequests(httpspixel.rubiconproject.com., 200);
    this.client.blacklistRequests(httpsplatform.twitter.com., 200);
    this.client.blacklistRequests(httpspx.steelhousemedia.com., 200);
    this.client.blacklistRequests(httpsr.turn.com., 200);
    this.client.blacklistRequests(httpsrc.rlcdn.com., 200);
    this.client.blacklistRequests(httpsrum - collector.pingdom.net., 200);
    this.client.blacklistRequests(httpss.tribalfusion.com., 200);
    this.client.blacklistRequests(httpss7.addthis.com., 200);
    this.client.blacklistRequests(httpssecure.adnxs.com., 200);
    this.client.blacklistRequests(httpssecure.brightcove.com., 200);
    this.client.blacklistRequests(httpssecure.fastclick.net., 200);
    this.client.blacklistRequests(httpssecure.img - cdn.mediaplex.com., 200);
    this.client.blacklistRequests(httpssecure.leadback.advertising.com., 200);
    this.client.blacklistRequests(httpssecure.leadback.com., 200);
    this.client.blacklistRequests(httpssecure - cdn.mplxtms.com., 200);
    this.client.blacklistRequests(httpsshutterfly - 2. custhelp.com., 200);
    this.client.blacklistRequests(httpssimage2.pubmatic.com., 200);
    this.client.blacklistRequests(httpssp.analytics.yahoo.com., 200);
    this.client.blacklistRequests(httpsstags.bluekai.com., 200);
    this.client.blacklistRequests(httpssync.adap.tv., 200);
    this.client.blacklistRequests(httpssync.adap.tv., 200);
    this.client.blacklistRequests(httpssync.adaptv.advertising.com., 200);
    this.client.blacklistRequests(httpssyndication.twitter.com., 200);
    this.client.blacklistRequests(httpstags.bkrtx.com., 200);
    this.client.blacklistRequests(httpstags.bluekai.com., 200);
    this.client.blacklistRequests(httpstapestry.tapad.com., 200);
    this.client.blacklistRequests(httpsus - u.openx.net., 200);
    this.client.blacklistRequests(httpsww.steelhousemedia.com., 200);
    this.client.blacklistRequests(httpswww.facebook.com., 200);
    this.client.blacklistRequests(httpswww.livelook.com., 200);
    this.client.blacklistRequests(httpswww.youtube.com., 200);
    this.client.blacklistRequests(httpsx.bidswitch.net., 200);
    this.client.blacklistRequests(httpswww.googleadservices.com., 200);
    this.client.blacklistRequests(httpswww.googlecommerce.com., 200);
    this.client.blacklistRequests(httpswww.gstatic.com., 200);
    this.client.blacklistRequests(httpscsi.gstatic.com., 200);
    this.client.blacklistRequests(httpsrum - static.pingdom.net., 200);
    this.client.blacklistRequests(httpsc.compete.com., 200);
    this.client.blacklistRequests(httpsimage2.pubmatic.com., 200);
    this.client.blacklistRequests(httpssimage2.pubmatic.com., 200);
    this.client.blacklistRequests(httpsp.analytics.yahoo.com., 200);
    this.client.blacklistRequests(httpssp.analytics.yahoo.com., 200);
    this.client.blacklistRequests(httpssync.adaptv.advertising.com., 200);
    this.client.blacklistRequests(httpssync.adap.tv., 200);
    this.client.blacklistRequests(httpstapestry.tapad.com., 200);
    this.client.blacklistRequests(httpssync.adaptv.advertising.com., 200);
    this.client.blacklistRequests(httpsanalytics.twitter.com., 200);
    this.client.blacklistRequests(httpsa.rfihub.com., 200);
    this.client.blacklistRequests(httpsstags.bluekai.com., 200);
    this.client.blacklistRequests(httpsrum - collector.pingdom.net., 200);
    this.client.blacklistRequests(httpspixel.rubiconproject.com., 200);
    this.client.blacklistRequests(httpstags.bkrtx.com., 200);
    this.client.blacklistRequests(httpsww.steelhousemedia.com., 200);
    this.client.blacklistRequests(httpscol.eum - appdynamics.com., 200);
    this.client.blacklistRequests(httpsapis.google.com., 200);
    this.client.blacklistRequests(httpsdsum - sec.casalemedia.com., 200);
    this.client.blacklistRequests(httpscdn.appdynamics.com., 200);
    this.client.blacklistRequests(httpspixel.quantserve.com., 200);
    this.client.blacklistRequests(httpsdx.steelhousemedia.com., 200);
    this.client.blacklistRequests(httpsa248.e.akamai.net., 200);
    this.client.blacklistRequests(httpscdn.syndication.twitter.com., 200);
    this.client.blacklistRequests(httpspx.steelhousemedia.com., 200);
    this.client.blacklistRequests(httpssecure.leadback.advertising.com., 200);
    this.client.blacklistRequests(httpsr.turn.com., 200);
    this.client.blacklistRequests(httpssecure.fastclick.net., 200);
    this.client.blacklistRequests(httpsadfarm.mediaplex.com., 200);
    this.client.blacklistRequests(httpsadadvisor.net., 200);
    this.client.blacklistRequests(httpsx.bidswitch.net., 200);
    this.client.blacklistRequests(httpsads.yahoo.com., 200);
    this.client.blacklistRequests(httpssecure.img - cdn.mediaplex.com., 200);
    this.client.blacklistRequests(httpssyndication.twitter.com., 200);
    this.client.blacklistRequests(httpssecure.adnxs.com., 200);
    this.client.blacklistRequests(httpseb2 .3 lift.com., 200);
    this.client.blacklistRequests(httpss7.addthis.com., 200);
    this.client.blacklistRequests(httpstags.bluekai.com., 200);
    this.client.blacklistRequests(httpsib.adnxs.com., 200);
    this.client.blacklistRequests(httpsbat.r.msn.com., 200);
    this.client.blacklistRequests(httpsbat.bing.com., 200);
    this.client.blacklistRequests(httpsei.rlcdn.com., 200);
    this.client.blacklistRequests(httpssecure.leadback.advertising.com., 200);
    this.client.blacklistRequests(httpssecure - cdn.mplxtms.com., 200);
    this.client.blacklistRequests(httpssecure.brightcove.com., 200);
    this.client.blacklistRequests(httpswww.youtube.com., 200);
    this.client.blacklistRequests(httpsplatform.twitter.com., 200);
    this.client.blacklistRequests(https20588869p.rfihub.com., 200);
    this.client.blacklistRequests(httpswww.facebook.com., 200);
    this.client.blacklistRequests(httpssecure.img - cdn.mediaplex.com., 200);
    this.client.blacklistRequests(httpsc.go - mpulse.net., 200);
    this.client.blacklistRequests(https36eb5594.mpstat.us., 200);
    this.client.blacklistRequests(httpsmatch.xg4ken.com., 200);
    this.client.blacklistRequests(httpswww.googleadservices.com., 200);
    this.client.blacklistRequests(httpswww.googlecommerce.com., 200);
    this.client.blacklistRequests(httpswww.gstatic.com., 200);
    this.client.blacklistRequests(httpscsi.gstatic.com., 200);
    this.client.blacklistRequests(httpsrum - static.pingdom.net., 200);
    this.client.blacklistRequests(httpsweb1.shutterfly.com., 200);
};
